/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonProfileManager;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.PersonProfile;
import model.PersonProfileDirectory;

/**
 *
 * @author varananavadiya
 */
public class ListPersonProfileJPanel extends javax.swing.JPanel {
    private PersonProfileDirectory profileDirectory;
    JPanel workAreaJPanel;
    private boolean showSearchResults;
    /**
     * Creates new form ListPersonProfileJPanel
     */
    public ListPersonProfileJPanel(JPanel workAreaJPanel,PersonProfileDirectory profileDirectory, boolean searchresult) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.profileDirectory = profileDirectory;
        this.showSearchResults = searchresult;
        System.out.println("Show search results: " + showSearchResults);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(111, 140, 177));
        setPreferredSize(new java.awt.Dimension(1119, 875));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("                                                                   List Person");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "HomeAddressCity", "HomeAddressZip", "WorkAddressCity", "WorkAddressZip"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btnView.setText("View Person Profile");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Profile");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(btnView)
                .addGap(35, 35, 35)
                .addComponent(btnDelete)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnView))
                .addGap(0, 273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
            int selectedRowIndex = jTable.getSelectedRow();
    
    if (selectedRowIndex < 0) {
        JOptionPane.showMessageDialog(this, "Please select a profile to view.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    ArrayList<PersonProfile> profilesToShow = showSearchResults ? profileDirectory.getSearchResults() : profileDirectory.getProfile();
    PersonProfile selectedProfile = profilesToShow.get(selectedRowIndex);
    
 
    ViewPersonProfileJPanel viewPanel = new ViewPersonProfileJPanel(workAreaJPanel, profileDirectory,selectedProfile );
    workAreaJPanel.add("ViewJPanel", viewPanel);
    
 
    CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
    layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                workAreaJPanel.remove(this);

       // Refresh the parent container
        Component[] panelStack = workAreaJPanel.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    int selectedRow = jTable.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this profile?", "Warning", JOptionPane.WARNING_MESSAGE);
            if (dialogResult == JOptionPane.YES_OPTION) {
                ArrayList<PersonProfile> profilesToShow = showSearchResults ? profileDirectory.getSearchResults() : profileDirectory.getProfile();
                PersonProfile selectedProfile = profilesToShow.get(selectedRow);
                profileDirectory.deleteProfile(selectedProfile);
                refreshPersonProfileList();  // Refresh the list after deletion
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select an account to delete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
     private void populateTable() {
DefaultTableModel model = (DefaultTableModel) jTable.getModel();
    model.setRowCount(0);  // Clear the table

    ArrayList<PersonProfile> profilesToShow = showSearchResults ? profileDirectory.getSearchResults() : profileDirectory.getProfile();

    for (PersonProfile profile : profilesToShow) {
        Object[] row = new Object[6];
        row[0] = profile.getFirstName();
        row[1] = profile.getLastName();
        row[2] = profile.getHomeCity();
        row[3] = profile.getHomeZipCode();
        row[4] = profile.getWorkCity();
        row[5] = profile.getWorkZipCode();
        model.addRow(row);  
    }
       
    }
    public void refreshPersonProfileList() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);  // Clear the existing table rows
        populateTable();  // Repopulate the table with the updated data
    }
}
