/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonProfileManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.PersonProfile;
import model.PersonProfileDirectory;

/**
 *
 * @author varananavadiya
 */
public class ViewPersonProfileJPanel extends javax.swing.JPanel {
    private PersonProfile profile;
    JPanel workAreaJPanel;
    private PersonProfileDirectory personProfileDirectory;
    private boolean isEditMode = false; 
    /**
     * Creates new form ViewPersonProfileJPanel
     */
    public ViewPersonProfileJPanel(JPanel workAreaJPanel,PersonProfileDirectory personProfileDirectory, PersonProfile selectedProfile) {
        initComponents();
        this.profile=selectedProfile;
        this.workAreaJPanel=workAreaJPanel;
        this.personProfileDirectory=personProfileDirectory;
        setViewMode();
        refreshTextFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void setViewMode() {

            txtFName.setEnabled(false);
            txtLName.setEnabled(false);
            txtAge.setEnabled(false);
            txtSSN.setEnabled(false);
            txtHCity.setEnabled(false);
            txtHPhoneNumber.setEnabled(false);
            txtHAddress.setEnabled(false);
            txtHState.setEnabled(false);
            txtHUnit.setEnabled(false);
            txtHZip.setEnabled(false);
            txtWCity.setEnabled(false);
            txtWPhoneNumber.setEnabled(false);
            txtWState.setEnabled(false);
            txtWAddress.setEnabled(false);
            txtWUnit.setEnabled(false);
            txtWZip.setEnabled(false);
            txtGender.setEnabled(false);
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        }
    
        private void setEditMode() {
            txtFName.setEnabled(true);
            txtLName.setEnabled(true);
            txtAge.setEnabled(true);
            txtSSN.setEnabled(true);
            txtHCity.setEnabled(true);
            txtHPhoneNumber.setEnabled(true);
            txtHAddress.setEnabled(true);
            txtHState.setEnabled(true);
            txtHUnit.setEnabled(true);
            txtHZip.setEnabled(true);
            txtWCity.setEnabled(true);
            txtWPhoneNumber.setEnabled(true);
            txtWState.setEnabled(true);
            txtWAddress.setEnabled(true);
            txtWUnit.setEnabled(true);
            txtWZip.setEnabled(true);
            txtGender.setEnabled(true);
            btnSave.setEnabled(true);
            btnUpdate.setEnabled(false);
        
    }
        private void refreshTextFields() {
            txtFName.setText(profile.getFirstName());
            txtLName.setText(profile.getLastName());
            txtAge.setText(String.valueOf(profile.getAge()));
            txtSSN.setText(String.valueOf(profile.getSsn()));
            txtGender.setText(String.valueOf(profile.getGender()));

            Address homeAddress = profile.getHomeAddress();
            txtHAddress.setText(homeAddress.getStreetAddress());
            txtHUnit.setText(homeAddress.getUnitNumber());
            txtHCity.setText(homeAddress.getCity());
            txtHState.setText(homeAddress.getState());
            txtHZip.setText(String.valueOf(homeAddress.getZipCode()));
            txtHPhoneNumber.setText(homeAddress.getPhoneNumber());


            Address workAddress = profile.getWorkAddress();
            txtWAddress.setText(workAddress.getStreetAddress());
            txtWUnit.setText(workAddress.getUnitNumber());
            txtWCity.setText(workAddress.getCity());
            txtWState.setText(workAddress.getState());
            txtWZip.setText(String.valueOf(workAddress.getZipCode()));
            txtWPhoneNumber.setText(workAddress.getPhoneNumber());

    }

            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblHCity = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtHUnit = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        txtHAddress = new javax.swing.JTextField();
        txtWAddress = new javax.swing.JTextField();
        lblHPhoneNumber = new javax.swing.JLabel();
        lblWAddress = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtHPhoneNumber = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        lblWUnit = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtHZip = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblHAddress = new javax.swing.JLabel();
        lblHZip = new javax.swing.JLabel();
        lblWState = new javax.swing.JLabel();
        lblHUnit = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblWZip = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        txtWZip = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtWUnit = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        txtWPhoneNumber = new javax.swing.JTextField();
        lblWPhoneNumber = new javax.swing.JLabel();
        txtHCity = new javax.swing.JTextField();
        txtWCity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(111, 140, 177));
        setPreferredSize(new java.awt.Dimension(1119, 875));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person");

        lblHCity.setText("City");

        lblWCity.setText("City");

        txtGender.setEnabled(false);

        lblHPhoneNumber.setText("Phone Number");

        lblWAddress.setText("Street Address");

        lblHState.setText("State");

        lblFName.setText("First Name");

        lblWUnit.setText("Unit Number");

        lblAge.setText("Age");

        txtHZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHZipActionPerformed(evt);
            }
        });

        lblSSN.setText("Social Security Number");

        lblHAddress.setText("Street Address");

        lblHZip.setText("Zip Code");

        lblWState.setText("State");

        lblHUnit.setText("Unit Number");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblWZip.setText("Zip Code");

        lblWorkAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblWorkAddress.setText("Work Address");

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblHomeAddress.setText("Home Address");

        lblGender.setText("Gender");

        lblLName.setText("Last Name");

        lblWPhoneNumber.setText("Phone Number");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWorkAddress)
                    .addComponent(lblGender)
                    .addComponent(lblFName)
                    .addComponent(lblSSN)
                    .addComponent(lblHZip)
                    .addComponent(lblWZip)
                    .addComponent(lblWAddress)
                    .addComponent(lblWCity)
                    .addComponent(lblHCity)
                    .addComponent(lblHAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAge))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(lblLName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblWState))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblWPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblWUnit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHState))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHUnit))
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(lblHomeAddress)
                    .addContainerGap(791, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHAddress)
                    .addComponent(txtHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHCity)
                    .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHState))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHPhoneNumber)
                    .addComponent(lblHZip))
                .addGap(31, 31, 31)
                .addComponent(lblWorkAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWUnit)
                    .addComponent(lblWAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWState)
                    .addComponent(lblWCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWPhoneNumber)
                    .addComponent(lblWZip))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(335, 335, 335)
                    .addComponent(lblHomeAddress)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        String ssn = txtSSN.getText();
        String age = txtAge.getText();
        String homeStreetAddress = txtHAddress.getText();
        String homeUnitNumber = txtHUnit.getText();
        String homeCity = txtHCity.getText();
        String homeState = txtHState.getText();
        String homeZipCode = txtHZip.getText();
        String homePhoneNumber = txtHPhoneNumber.getText();
        String workStreetAddress = txtWAddress.getText();
        String workUnitNumber = txtWUnit.getText();
        String workCity = txtWCity.getText();
        String workState = txtWState.getText();
        String workZipCode = txtWZip.getText();
        String workPhoneNumber = txtWPhoneNumber.getText();
        String genderInput = txtGender.getText();
    
        if (fName.isBlank() || lName.isBlank() || ssn.isBlank() || age.isBlank() || homeStreetAddress.isBlank() ||
            homeUnitNumber.isBlank() || homeState.isBlank() || homeCity.isBlank() || homePhoneNumber.isBlank() ||
            homeZipCode.isBlank() || workStreetAddress.isBlank() || workCity.isBlank() || workState.isBlank() ||
            workZipCode.isBlank() || workPhoneNumber.isBlank() || genderInput.isBlank()) {
            JOptionPane.showMessageDialog(this, "All the fields are required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        long ssNumber;
        int Age;
        char gender;
        try {
            ssNumber = Long.parseLong(ssn);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric SSN", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Age = Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric Age", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

      
        if (ssn.length() != 9) {
            JOptionPane.showMessageDialog(this, "SSN must have 9 numeric values", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (genderInput.length() != 1 || !(genderInput.equalsIgnoreCase("M") || genderInput.equalsIgnoreCase("F"))) {
            JOptionPane.showMessageDialog(this, "Gender must be 'M' or 'F'", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            gender = genderInput.charAt(0);
        }
        
        if (homeZipCode.length() != 5 && homeZipCode.length() != 7) {
            JOptionPane.showMessageDialog(this, "Home ZIP code must be 5 or 7 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (workZipCode.length() != 5 && workZipCode.length() != 7) {
            JOptionPane.showMessageDialog(this, "Work ZIP code must be 5 or 7 characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (homePhoneNumber.length() != 10) {
            JOptionPane.showMessageDialog(this, "Home Phone Number must be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (workPhoneNumber.length() != 10) {
            JOptionPane.showMessageDialog(this, "Work Phone Number must be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Age <= 0 || Age > 120) {
            JOptionPane.showMessageDialog(this, "Age must be between 1 and 120", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        profile.setFirstName(fName);
        profile.setLastName(lName);
        profile.setSsn(ssNumber);
        profile.setAge(Age);
        profile.setGender(gender);
    
        Address homeAddress = new Address();
        homeAddress.setStreetAddress(homeStreetAddress);
        homeAddress.setUnitNumber(homeUnitNumber);
        homeAddress.setCity(homeCity);
        homeAddress.setState(homeState);
        homeAddress.setZipCode(homeZipCode);
        homeAddress.setPhoneNumber(homePhoneNumber);
        profile.setHomeAddress(homeAddress); 

        Address workAddress = new Address();
        workAddress.setStreetAddress(workStreetAddress);
        workAddress.setUnitNumber(workUnitNumber);
        workAddress.setCity(workCity);
        workAddress.setState(workState);
        workAddress.setZipCode(workZipCode);
        workAddress.setPhoneNumber(workPhoneNumber);
        profile.setWorkAddress(workAddress);
        setViewMode();
    
        JOptionPane.showMessageDialog(this, "Profile Successfully Updated", "Success", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        Component[] panelStack = workAreaJPanel.getComponents();
        for (Component comp : panelStack) {
            if (comp instanceof ListPersonProfileJPanel) {
                ListPersonProfileJPanel listPanel = (ListPersonProfileJPanel) comp;
                listPanel.refreshPersonProfileList();  // Refresh the list after the update
            }
        }

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtHZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHZipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHAddress;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHPhoneNumber;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHUnit;
    private javax.swing.JLabel lblHZip;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWAddress;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWPhoneNumber;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWUnit;
    private javax.swing.JLabel lblWZip;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHAddress;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHPhoneNumber;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHUnit;
    private javax.swing.JTextField txtHZip;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWAddress;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWPhoneNumber;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWUnit;
    private javax.swing.JTextField txtWZip;
    // End of variables declaration//GEN-END:variables
}
