/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.PersonProfile;

/**
 *
 * @author varananavadiya
 */
public class CreateJPanel extends javax.swing.JPanel {
    PersonProfile personprofile;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(PersonProfile pf) {
        personprofile=pf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtdln = new javax.swing.JTextField();
        txtdls = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtaddress1 = new javax.swing.JTextField();
        txtaddress2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        txttelephonenumber = new javax.swing.JTextField();
        txtfaxnumber = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtnationality = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtoccupation = new javax.swing.JTextField();
        txtmaritalstatus = new javax.swing.JTextField();
        txteducationlevel = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lbldln = new javax.swing.JLabel();
        lbldls = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lbladdress1 = new javax.swing.JLabel();
        lbladdress2 = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblzip = new javax.swing.JLabel();
        lbltelephonenumber = new javax.swing.JLabel();
        lblfaxnumber = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblnationality = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lbloccupation = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblmaritalstatus = new javax.swing.JLabel();
        lbleducationlevel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtaddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddress1ActionPerformed(evt);
            }
        });

        txttelephonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelephonenumberActionPerformed(evt);
            }
        });

        lblfname.setText("First Name");

        lbllname.setText("Last Name");

        lblemail.setText("Email");

        lblphone.setText("Phone No.");

        lbldln.setText("Driver License No.");

        lbldls.setText("Driver License Status");

        lblssn.setText("Social Security No.");

        lbladdress1.setText("Address1");

        lbladdress2.setText("Address2");

        lblcity.setText("City");

        lblzip.setText("ZIP");

        lbltelephonenumber.setText("Telephone No.");

        lblfaxnumber.setText("Fax No.");

        lbldob.setText("DOB");

        lblnationality.setText("Nationality");

        lblgender.setText("Gender");

        lbloccupation.setText("Occupation");

        lblstate.setText("State");

        lblmaritalstatus.setText("Marital Status");

        lbleducationlevel.setText("Educational Level");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbltitle.setText("                                                      Create Person Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnationality)
                    .addComponent(lbllname)
                    .addComponent(lblfname)
                    .addComponent(lblemail)
                    .addComponent(lblphone)
                    .addComponent(lbldln)
                    .addComponent(lbldls)
                    .addComponent(lblssn)
                    .addComponent(lbldob)
                    .addComponent(lblgender)
                    .addComponent(lbleducationlevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtdob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtdln)
                    .addComponent(txtemail)
                    .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdls)
                    .addComponent(txtssn)
                    .addComponent(txtfname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfaxnumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnationality, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txteducationlevel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcity, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblstate, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblzip, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(110, 110, 110)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbladdress1)
                                        .addComponent(lbladdress2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmaritalstatus, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbloccupation, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblfaxnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbltelephonenumber, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtcity)
                            .addComponent(txtoccupation)
                            .addComponent(txtstate)
                            .addComponent(txtzip)
                            .addComponent(txttelephonenumber)
                            .addComponent(txtgender)
                            .addComponent(txtmaritalstatus)
                            .addComponent(txtaddress1))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllname)
                    .addComponent(txtaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdress2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone)
                    .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldln, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldls)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelephonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblssn)
                    .addComponent(txttelephonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfaxnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(txtfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbloccupation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblgender))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmaritalstatus)
                        .addComponent(txtmaritalstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnationality))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteducationlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbleducationlevel)
                    .addComponent(btnSave))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtaddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddress1ActionPerformed

    private void txttelephonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelephonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelephonenumberActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            // TODO add your handling code here:
            String fname=txtfname.getText();
            String lname=txtlname.getText();
            String mail=txtemail.getText();
            String phn=txtphone.getText();
            String dln=txtdln.getText();
            String dls=txtdls.getText();
            String socialsecnum=txtssn.getText();
            String add1=txtaddress1.getText();
            String add2=txtaddress2.getText();
            String city=txtcity.getText();
            String state=txtstate.getText();
            String zip=txtzip.getText();
            String tn=txttelephonenumber.getText();
            String fn=txtfaxnumber.getText();
            String dob=txtdob.getText();
            String nationality=txtnationality.getText();
            String gender=txtgender.getText();
            String occup=txtoccupation.getText();
            String maritalstat=txtmaritalstatus.getText();
            String edulevel=txteducationlevel.getText();
            
            personprofile.setFirstName(fname);
            personprofile.setLastName(lname);
            personprofile.setEmail(mail);
            personprofile.setPhone(phn);
            personprofile.setDriverLicenseNumber(dln);
            personprofile.setDriverLicenseStatus(dls);
            personprofile.setSsn(socialsecnum);
            personprofile.setAddress1(add1);
            personprofile.setAddress2(add2);
            personprofile.setCity(city);
            personprofile.setState(state);
            personprofile.setZip(zip);
            personprofile.setTelephoneNumber(tn);
            personprofile.setFaxNumber(fn);
            personprofile.setDob(dob);
            personprofile.setNationality(nationality);
            personprofile.setGender(gender);
            personprofile.setOccupation(occup);
            personprofile.setMaritalStatus(maritalstat);
            personprofile.setEducationLevel(edulevel);       
            
            JOptionPane.showMessageDialog(this,"Person Profile Saved","Success",JOptionPane.PLAIN_MESSAGE);
            
            txtfname.setText("");
            txtlname.setText("");
            txtemail.setText("");
            txtphone.setText("");
            txtdln.setText("");
            txtdls.setText("");
            txtssn.setText("");
            txtaddress1.setText("");
            txtaddress2.setText("");
            txtcity.setText("");
            txtstate.setText("");
            txtzip.setText("");
            txttelephonenumber.setText("");
            txtfaxnumber.setText("");
            txtdob.setText("");
            txtnationality.setText("");
            txtgender.setText("");
            txtoccupation.setText("");
            txtmaritalstatus.setText("");
            txteducationlevel.setText("");        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbladdress1;
    private javax.swing.JLabel lbladdress2;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbldln;
    private javax.swing.JLabel lbldls;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbleducationlevel;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfaxnumber;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblmaritalstatus;
    private javax.swing.JLabel lblnationality;
    private javax.swing.JLabel lbloccupation;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lbltelephonenumber;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblzip;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress2;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdln;
    private javax.swing.JTextField txtdls;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txteducationlevel;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaxnumber;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmaritalstatus;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txttelephonenumber;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
