/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.PersonProfileDirectory;
import ui.PersonProfileManager.AddPersonProfileJPanel;
import ui.PersonProfileManager.ListPersonProfileJPanel;
import javax.swing.JOptionPane;
import model.Address;
import model.PersonProfile;

/**
 *
 * @author varananavadiya
 */
public class MainJFrame extends javax.swing.JFrame {

    private PersonProfileDirectory profileDirectory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        txtSearchPerson.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (txtSearchPerson.getText().equals("Type name or street address")) {
            txtSearchPerson.setText("");
            txtSearchPerson.setForeground(new java.awt.Color(0, 0, 0)); // Set text color to black
        }
    }
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (txtSearchPerson.getText().trim().isEmpty()) {
            txtSearchPerson.setForeground(new java.awt.Color(204, 204, 204)); // Set text color back to gray
            txtSearchPerson.setText("Type name or street address");
        }
    }
});
        this.profileDirectory = new PersonProfileDirectory();
        demoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane1 = new javax.swing.JSplitPane();
        menuJPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAddPerson = new javax.swing.JButton();
        btnListPerson = new javax.swing.JButton();
        btnSearchPerson = new javax.swing.JButton();
        txtSearchPerson = new javax.swing.JTextField();
        workAreaJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuJPanel.setBackground(new java.awt.Color(111, 140, 177));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Profile");

        btnAddPerson.setText("Add Person");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnListPerson.setText("List Person");
        btnListPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonActionPerformed(evt);
            }
        });

        btnSearchPerson.setText("Search for Person");
        btnSearchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPersonActionPerformed(evt);
            }
        });

        txtSearchPerson.setForeground(new java.awt.Color(204, 204, 204));
        txtSearchPerson.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchPerson.setText("Type name or street address");
        txtSearchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuJPanelLayout = new javax.swing.GroupLayout(menuJPanel);
        menuJPanel.setLayout(menuJPanelLayout);
        menuJPanelLayout.setHorizontalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnAddPerson)
                .addGap(18, 18, 18)
                .addComponent(btnListPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtSearchPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchPerson)
                .addGap(172, 172, 172))
        );
        menuJPanelLayout.setVerticalGroup(
            menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJPanelLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(menuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPerson)
                    .addComponent(btnListPerson)
                    .addComponent(btnSearchPerson)
                    .addComponent(txtSearchPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        splitPane1.setTopComponent(menuJPanel);

        workAreaJPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO PERSON PROFILE!");
        workAreaJPanel.add(jLabel1, "card2");

        splitPane1.setRightComponent(workAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        AddPersonProfileJPanel panel = new AddPersonProfileJPanel(workAreaJPanel, profileDirectory);
        workAreaJPanel.add("AddPersonJPanel", panel);

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void txtSearchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPersonActionPerformed
        // TODO add your handling code here:
        if (txtSearchPerson.getForeground().equals(new java.awt.Color(204, 204, 204))) {
        txtSearchPerson.setText(""); // Clear text
        txtSearchPerson.setForeground(new java.awt.Color(0, 0, 0)); // Set text color to black
    }
    }//GEN-LAST:event_txtSearchPersonActionPerformed

    
    private void btnListPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonActionPerformed
        // TODO add your handling code here:
        ListPersonProfileJPanel panel = new ListPersonProfileJPanel(workAreaJPanel, profileDirectory, false);
        workAreaJPanel.add("ListPersonJPanel", panel);

        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnListPersonActionPerformed

    private void btnSearchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPersonActionPerformed
        // TODO add your handling code here:
        String searchInput = txtSearchPerson.getText().trim();  
        if (searchInput.isEmpty()) {

           JOptionPane.showMessageDialog(this, "Please enter a search term.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }else{

        profileDirectory.searchProfile(searchInput);  
        for (PersonProfile p : profileDirectory.getSearchResults()) {
            // Print attributes of the PersonalProfile object
            System.out.println("First Name: " + p.getFirstName());
            System.out.println("Last Name: " + p.getLastName());
            System.out.println("Age: " + p.getAge());
        }
        
        if (profileDirectory.getSearchResults().isEmpty()) {

            JOptionPane.showMessageDialog(this, "No matching profiles found.", "Search Results", JOptionPane.PLAIN_MESSAGE);
        } else {
          
            ListPersonProfileJPanel panel = new ListPersonProfileJPanel(workAreaJPanel, profileDirectory, true);  
            workAreaJPanel.add("ListPersonProfileJPanel", panel);
           
            CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
            layout.next(workAreaJPanel);
            txtSearchPerson.setText("");
        }
    }
    }//GEN-LAST:event_btnSearchPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnListPerson;
    private javax.swing.JButton btnSearchPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JSplitPane splitPane1;
    private javax.swing.JTextField txtSearchPerson;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables

    private void demoData() {
        PersonProfile newProfile1 = new PersonProfile();
        newProfile1.setFirstName("Varana");
        newProfile1.setLastName("Navadiya");
        newProfile1.setSsn(123456789);
        newProfile1.setAge(23);
        newProfile1.setGender('F');

         
        Address homeAddress1 = new Address();
        homeAddress1.setStreetAddress("110 Warren St");
        homeAddress1.setUnitNumber("Apt 2");
        homeAddress1.setCity("Boston");
        homeAddress1.setState("MA");
        homeAddress1.setZipCode("02135");
        homeAddress1.setPhoneNumber("1234567890");
        newProfile1.setHomeAddress(homeAddress1);  // Set home address

        Address workAddress1 = new Address();
        workAddress1.setStreetAddress("50 Island View");
        workAddress1.setUnitNumber("Apt 601");
        workAddress1.setCity("Boston");
        workAddress1.setState("MA");
        workAddress1.setZipCode("02125");
        workAddress1.setPhoneNumber("0000000000");
        newProfile1.setWorkAddress(workAddress1);  // Set work address

        profileDirectory.addProfile(newProfile1);

        PersonProfile newProfile2 = new PersonProfile();
        newProfile2.setFirstName("Megha");
        newProfile2.setLastName("Shah");
        newProfile2.setSsn(987654321);
        newProfile2.setAge(28);
        newProfile2.setGender('F');
        
        Address homeAddress2 = new Address();
        homeAddress2.setStreetAddress("15 Cambridge St");
        homeAddress2.setUnitNumber("Apt 9");
        homeAddress2.setCity("Boston");
        homeAddress2.setState("MA");
        homeAddress2.setZipCode("02134");
        homeAddress2.setPhoneNumber("0987654321");
        newProfile2.setHomeAddress(homeAddress2);  // Set home address

        Address workAddress2 = new Address();
        workAddress2.setStreetAddress("200 Harvard Ave");
        workAddress2.setUnitNumber("Suite 300");
        workAddress2.setCity("Cambridge");
        workAddress2.setState("MA");
        workAddress2.setZipCode("02125");
        workAddress2.setPhoneNumber("9876543210");
        newProfile2.setWorkAddress(workAddress2);  // Set work address

        profileDirectory.addProfile(newProfile2);

        // Similar changes for other profiles
        PersonProfile newProfile3 = new PersonProfile();
        newProfile3.setFirstName("Raj");
        newProfile3.setLastName("Desai");
        newProfile3.setSsn(123987456);
        newProfile3.setAge(32);
        newProfile3.setGender('M');

        Address homeAddress3 = new Address();
        homeAddress3.setStreetAddress("234 Beacon St");
        homeAddress3.setUnitNumber("Apt 4B");
        homeAddress3.setCity("Newton");
        homeAddress3.setState("MA");
        homeAddress3.setZipCode("02115");
        homeAddress3.setPhoneNumber("1239876543");
        newProfile3.setHomeAddress(homeAddress3);  // Set home address

        Address workAddress3 = new Address();
        workAddress3.setStreetAddress("500 Main St");
        workAddress3.setUnitNumber("Office 501");
        workAddress3.setCity("Boston");
        workAddress3.setState("MA");
        workAddress3.setZipCode("02110");
        workAddress3.setPhoneNumber("1230004567");
        newProfile3.setWorkAddress(workAddress3);  // Set work address

        profileDirectory.addProfile(newProfile3);
        
        PersonProfile newProfile4 = new PersonProfile();
        newProfile4.setFirstName("Pooja");
        newProfile4.setLastName("Patel");
        newProfile4.setSsn(567890123);
        newProfile4.setAge(26);
        newProfile4.setGender('F');

        Address homeAddress4 = new Address();
        homeAddress4.setStreetAddress("567 Commonwealth Ave");
        homeAddress4.setUnitNumber("Apt 7A");
        homeAddress4.setCity("Brookline");
        homeAddress4.setState("MA");
        homeAddress4.setZipCode("02446");
        homeAddress4.setPhoneNumber("5678901234");
        newProfile4.setHomeAddress(homeAddress4);  // Set home address

        Address workAddress4 = new Address();
        workAddress4.setStreetAddress("150 Boylston St");
        workAddress4.setUnitNumber("Suite 700");
        workAddress4.setCity("Boston");
        workAddress4.setState("MA");
        workAddress4.setZipCode("02116");
        workAddress4.setPhoneNumber("5678904321");
        newProfile4.setWorkAddress(workAddress4);  // Set work address

        profileDirectory.addProfile(newProfile4);

        PersonProfile newProfile5 = new PersonProfile();
        newProfile5.setFirstName("Kunal");
        newProfile5.setLastName("Joshi");
        newProfile5.setSsn(112233445);
        newProfile5.setAge(29);
        newProfile5.setGender('M');

        Address homeAddress5 = new Address();
        homeAddress5.setStreetAddress("789 Washington St");
        homeAddress5.setUnitNumber("Apt 12");
        homeAddress5.setCity("Somerville");
        homeAddress5.setState("MA");
        homeAddress5.setZipCode("02145");
        homeAddress5.setPhoneNumber("1122334455");
        newProfile5.setHomeAddress(homeAddress5);  // Set home address

        Address workAddress5 = new Address();
        workAddress5.setStreetAddress("100 State St");
        workAddress5.setUnitNumber("Floor 5");
        workAddress5.setCity("Boston");
        workAddress5.setState("MA");
        workAddress5.setZipCode("02116");
        workAddress5.setPhoneNumber("1122330099");
        newProfile5.setWorkAddress(workAddress5);  // Set work address

        profileDirectory.addProfile(newProfile5);
        
    }
}
